### ISSUE TITLE
hyperf核心升级到3.1.39后启动报错未实现collectClassConstant方法[BUG] #1

### ISSUE THREAD

**Issue by xu767142206** [lazychanger/hyperf-helper-dependency#4]
由于hyperf核心升级增加了新的方法，需要实现一个collectClassConstant函数

暂时改成这样就好了，希望作者可以做版本兼容

`#[Attribute(Attribute::TARGET_CLASS)]
class Dependency implements AnnotationInterface
{

    // **** 代码已省略

  
    /**
     * Collect the annotation metadata to a container that you want.
     */
    public function collectClassConstant(string $className, ?string $target): void
    {
    }
}`

**Comment by lazychanger** [comment]
我看一下

**Comment by lazychanger** [comment]
@xu767142206 已经更新了，拉取一下最新的v1.1看看。
